name: Deploy to Amazon ECS
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-18.04
    
    steps:    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        SSH_PRIVATE_KEY: ${ { secrets.AWS_PRIVATE_KEY }}
        REMOTE_HOST: ${ { secrets.HOST }}
        REMOTE_USER: ${ { secrets.USERNAME }}
        aws-region: ${{ env.AWS_REGION }}

      
    - name: Cache node modules  # node modules 캐싱
      uses: actions/cache@v1
      with:
          path: node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
            
    - run: npm install
    - run: sudo pm2 restart server
