name: Deploy to Amazon ECS
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the files
      uses: actions/checkout@v2
      
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${ { secrets.AWS_PRIVATE_KEY }}
        REMOTE_HOST: ${ { secrets.HOST }}
        REMOTE_USER: ${ { secrets.USERNAME }}
        TARGET: ${ { secrets.TARGET_DIR }}
        
    - run: npm install
    - run: sudo pm2 restart server
