name: Deploy to Amazon ECS
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-18.04
    
    steps:
    - name: Checkout the files
      uses: actions/checkout@v2
      
    - name: Cache node modules  # node modules 캐싱
      uses: actions/cache@v1
      with:
          path: node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

    - name: Build # project build
      run: npm build
      
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${ { secrets.AWS_PRIVATE_KEY }}
        REMOTE_HOST: ${ { secrets.HOST }}
        REMOTE_USER: ${ { secrets.USERNAME }}
        
    - run: npm install
    - run: sudo pm2 restart server
